name: gema
description: Applikasi GEMA

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.15+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # firebase_core: "^0.5.0"
  # cloud_firestore: ^0.14.0+2
  # firebase_auth: ^0.18.0+1
#  http: ^0.12.2
  http: ^0.13.0
  device_info: ^2.0.0
  global_configuration: ^2.0.0-nullsafety.1
  google_nav_bar: ^3.1.0
  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  # path_provider: ^2.0.7
  scroll_to_index: ^2.0.0
  share: ^2.0.1
#  flutter_local_notifications: ^9.1.5
  flutter_secure_storage: ^6.0.0
  sendgrid_mailer: ^0.1.2
  graphql_flutter: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_launcher-3.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - pubspec.yaml
    - assets/cfg/
    - assets/cfg/gema.db
    - assets/images/
    - assets/backgrounds/
    - assets/fonts/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
#    - family: FiraSansCondensed
#      fonts:
#        - asset: assets/fonts/FiraSansCondensed/FiraSansCondensed-Regular.ttf
#        - asset: assets/fonts/FiraSansCondensed/FiraSansCondensed-Bold.ttf
#          weight: 600
#        - asset: assets/fonts/FiraSansCondensed/FiraSansCondensed-BoldItalic.ttf
#          weight: 600
#        - asset: assets/fonts/FiraSansCondensed/FiraSansCondensed-Italic.ttf
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans/FiraSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/FiraSans/FiraSans-ThinItalic.ttf
          weight: 100
        - asset: assets/fonts/FiraSans/FiraSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/FiraSans/FiraSans-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/FiraSans/FiraSans-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraSans/FiraSans-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/FiraSans/FiraSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraSans/FiraSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/FiraSans/FiraSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraSans/FiraSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/FiraSans/FiraSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraSans/FiraSans-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/FiraSans/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/FiraSans/FiraSans-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/FiraSans/FiraSans-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/FiraSans/FiraSans-ExtraBoldItalic.ttf
          weight: 700
        - asset: assets/fonts/FiraSans/FiraSans-Black.ttf
          weight: 900
        - asset: assets/fonts/FiraSans/FiraSans-BlackItalic.ttf
          weight: 900

    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
